import * as THREE from 'three';
import {detailedSurface,type World} from './world';
// Pilot v2: edge-centered skylight and camera-relative input.
// Explicit pilot bounds, independent of decorative rendering geometry.
export const PILOT={street:{x0:-39,x1:-13,z0:1,z1:7},room:{x0:-38,x1:-31,z0:7,z1:12},glass:{x0:-27.480762,x1:-24.480762,z0:2,z1:6},shaft:{x0:-20,x1:-18,z0:5,z1:7},floor:-9};
export function inRect(x:number,z:number,r:{x0:number;x1:number;z0:number;z1:number},margin=0){return x>=r.x0+margin&&x<=r.x1-margin&&z>=r.z0+margin&&z<=r.z1-margin;}
export const OCT10_SHAFTS=[{x:-15*Math.sqrt(3),z:39.6},{x:-35*Math.sqrt(3),z:-50.4},{x:-25*Math.sqrt(3),z:-18.6}].map(p=>({x0:p.x-1,x1:p.x+1,z0:p.z-1,z1:p.z+1}));
export const REVIEW_SHAFTS=[{x:-20*Math.sqrt(3),z:2.7},{x:-10*Math.sqrt(3),z:1.8}].map(p=>({x0:p.x-1,x1:p.x+1,z0:p.z-1,z1:p.z+1}));
export function pilotOpening(x:number,z:number){return inRect(x,z+4,PILOT.glass)||inRect(x,z+4,PILOT.shaft)||OCT10_SHAFTS.some(r=>inRect(x,z,r))||REVIEW_SHAFTS.some(r=>inRect(x,z,r))||inRect(x,z,{x0:-15*Math.sqrt(3)-1.5,x1:-15*Math.sqrt(3)+1.5,z0:-2,z1:2});}
export function movementVector(yaw:number,right:number,forward:number){return {x:-Math.sin(yaw)*forward+Math.cos(yaw)*right,z:-Math.cos(yaw)*forward-Math.sin(yaw)*right};}
export function walkable(x:number,z:number){for(const px of [-37,-31,-21,-15])if(Math.abs(x-(px+1.1))<.38&&Math.abs(z-6.8)<.22||Math.abs(x-px)<.8&&Math.abs(z-6.75)<.12)return false;for(const tx of [-36,-33])if(Math.abs(x-tx)<.44&&Math.abs(z-8.5)<.4)return false;if(x>-35.85&&x<-32.15&&z>10.05)return false;return inRect(x,z,PILOT.street,.35)||inRect(x,z,PILOT.room,.35)||(x>-37.65&&x<-31.35&&z>6.3&&z<7.7);}
export class Underground {
 group=new THREE.Group();avatar=new THREE.Group();active=false;level:'street'|'surface'|'atelier'='street';movingLift=false;position=new THREE.Vector3(-19,PILOT.floor,6);keys=new Set<string>();private ui:HTMLDivElement;private oldPos=new THREE.Vector3();private oldTarget=new THREE.Vector3();private feet:THREE.Mesh[]=[];private liftGoal=0;private liftKind:'surface'|'atelier'='surface';private atelierPlatform!:THREE.Mesh;private liftPlatform!:THREE.Mesh;private phase=0;private lookUp=false;private yaw=Math.PI/2;private pitch=.12;private eyeView=false;private lookStick=new THREE.Vector2();private ground:(x:number,z:number)=>number;
 constructor(private world:World,ground:(x:number,z:number)=>number){this.ground=(x,z)=>ground(x,z-4);this.group.name='underground-pilot';world.scene.add(this.group);this.build();this.group.position.z=-4;this.ui=document.createElement('div');this.ui.className='underground-ui';this.ui.innerHTML='<button class="ug-start">⌄ תת קרקע</button><div class="ug-panel" hidden><div class="ug-status"></div><div class="ug-hint">WASD / חצים · E פעולה · Esc מבט על</div><div class="ug-switch"><button data-area="pilot" disabled aria-pressed="true">מעברים</button></div><div class="ug-actions"><button data-ug="lift">↕ מעלית</button><button data-ug="eye">◉ מבט עיניים</button><button data-ug="look">⇧ מבט דרך הגג</button><button data-ug="reset">⌖ חזרה לכניסה</button><button data-ug="exit">מבט על ↗</button></div><div class="ug-pad"><button data-key="ArrowUp">▲</button><div><button data-key="ArrowLeft">◀</button><button data-key="ArrowDown">▼</button><button data-key="ArrowRight">▶</button></div></div><div class="ug-look" aria-label="Look joystick"><span>מבט</span><i></i></div></div>';world.renderer.domElement.parentElement!.append(this.ui);
 this.ui.querySelector('[data-ug=eye]')!.addEventListener('click',()=>{this.eyeView=!this.eyeView;this.lookUp=false;});const stick=this.ui.querySelector<HTMLDivElement>('.ug-look')!;let lookId:number|undefined;const lookMove=(e:PointerEvent)=>{if(e.pointerId!==lookId)return;const r=stick.getBoundingClientRect();this.lookStick.set(THREE.MathUtils.clamp((e.clientX-r.x-r.width/2)/(r.width/2),-1,1),THREE.MathUtils.clamp((e.clientY-r.y-r.height/2)/(r.height/2),-1,1));(stick.querySelector('i') as HTMLElement).style.transform=`translate(${this.lookStick.x*22}px,${this.lookStick.y*22}px)`;};stick.addEventListener('pointerdown',e=>{e.preventDefault();lookId=e.pointerId;stick.setPointerCapture(e.pointerId);lookMove(e)});stick.addEventListener('pointermove',lookMove);for(const ev of ['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(ev,()=>{lookId=undefined;this.lookStick.set(0,0);(stick.querySelector('i') as HTMLElement).style.transform='';});this.ui.querySelector('.ug-start')!.addEventListener('click',()=>this.enter());this.ui.querySelector('[data-ug=exit]')!.addEventListener('click',()=>this.exit());this.ui.querySelector('[data-ug=look]')!.addEventListener('click',()=>this.lookUp=!this.lookUp);this.ui.querySelector('[data-ug=lift]')!.addEventListener('click',()=>this.lift());this.ui.querySelector('[data-ug=reset]')!.addEventListener('click',()=>{this.lookUp=false;this.yaw=Math.PI/2;this.pitch=.12;this.keys.clear();this.lookStick.set(0,0);this.position.set(-19,PILOT.floor,6);this.level='street';this.movingLift=false;});
 for(const b of Array.from(this.ui.querySelectorAll<HTMLButtonElement>('[data-key]'))){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);this.keys.add(b.dataset.key!)});for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,()=>this.keys.delete(b.dataset.key!));}
 window.addEventListener('keydown',e=>{if(!this.active||/INPUT|TEXTAREA|SELECT/.test((e.target as HTMLElement).tagName))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD','Space'].includes(e.code)){e.preventDefault();this.keys.add(e.code)}if(e.code==='Escape')this.exit();if(e.code==='KeyE'&&!e.repeat)this.lift();});window.addEventListener('keyup',e=>this.keys.delete(e.code));window.addEventListener('blur',()=>this.keys.clear());this.world.catalogJoints(this.group);this.avatar.visible=false;
 }
 private mat(color:string,glow=false){if(glow)return new THREE.MeshBasicMaterial({color});const maps=detailedSurface('stone');return new THREE.MeshStandardMaterial({color,map:maps.color,normalMap:maps.normal,normalScale:new THREE.Vector2(.3,.3),roughnessMap:maps.rough,roughness:.9,metalness:.2});}
 private box(w:number,h:number,d:number,x:number,y:number,z:number,mat:THREE.Material){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.receiveShadow=true;this.group.add(m);return m;}
 private build(){const p=PILOT,base=this.mat('#344851'),wall=this.mat('#677b80'),warm=this.mat('#cfbca4'),cyan=this.mat('#70ddea',true),yellow=this.mat('#e6b667',true);this.box(26,.3,6,-26,-9.15,4,base);this.box(7,.3,5,-34.5,-9.15,9.5,warm);
 // A road reserve with two sidewalks. These markings are not a driving mode.
 for(const z of [1.65,6.35]){this.box(26,.12,1.15,-26,-8.94,z,wall);this.box(26,.025,.06,-26,-8.86,z+(z<4?.6:-.6),cyan);}for(let x=-38;x<-13;x+=2)this.box(.8,.025,.06,x,-8.96,4,yellow);
 for(let x=-38;x<=-14;x+=3){this.box(.09,4,.14,x,-7,1.04,warm);this.box(.09,4,.14,x,-7,6.97,warm);this.box(1.3,.9,.08,x,-7.2,1.04,this.mat('#325661'));}this.box(26,5,.22,-26,-6.5,.9,wall);for(const [x,w] of [[-38.5,1],[-22,18]])this.box(w,5,.22,x,-6.5,7.1,wall);for(const x of [-39.1,-12.9])this.box(.22,5,6,x,-6.5,4,wall);this.box(7,4,.18,-34.5,-7,12.1,wall);for(const x of [-38.1,-30.9])this.box(.18,4,5,x,-7,9.5,wall);
 // Two access plazas beneath the existing building centers, connected by the road.
 for(const x of [-34.64,-17.32]){this.box(4,.025,3.6,x,-8.91,4,warm);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.15,.035,5,32),cyan);ring.rotation.x=Math.PI/2;ring.position.set(x,-8.85,4);this.group.add(ring);this.sign('BUILDING ACCESS / LIFT',x,-6.8,1.2);}
 for(const x of [-37,-31,-21,-15]){this.box(1.5,.18,.4,x,-8.7,6.75,warm);this.box(1.5,.5,.12,x,-8.4,6.92,wall);this.box(.5,.35,.6,x+1.1,-8.75,6.8,base);this.world.catalogTree(this.group,x+1.1,-8.57,6.8,Math.abs(x)%3,'underground-'+x,.9);}
 for(const x of [-36,-33]){this.box(.75,.05,.65,x,-8.38,8.5,warm);this.box(.06,.55,.06,x,-8.7,8.5,wall);for(const z of [7.9,9.1]){this.box(.4,.08,.4,x,-8.65,z,warm);this.box(.4,.35,.06,x,-8.45,z+.17,wall);}}
 this.sign('CAFE / ATELIER',-34.5,-6.5,9.5);this.atelierPlatform=this.box(1.1,.12,1.1,-32,-9.08,9.7,cyan);for(const x of [-32.6,-31.4])this.box(.04,2.7,.04,x,-7.6,9.1,cyan);this.sign('ATELIER LIFT / LEVEL 01',-32,-6.7,9.7);this.box(2.5,.1,2.2,-32.5,-6.35,9.5,warm);
 // Surface-conforming ceiling pieces leave glass and access apertures genuinely open.
 for(let x=-38.5;x<-13;x++)for(let z=1.5;z<7;z++){if(!pilotOpening(x,z-4))this.box(1.01,.16,1.01,x,this.ground(x,z)+.17,z,base);}
 const glass=new THREE.MeshPhysicalMaterial({color:'#b9e5e6',transparent:true,opacity:.22,roughness:.12,metalness:.12,side:THREE.DoubleSide,depthWrite:false});for(let i=0;i<3;i++)for(let z=2.5;z<6;z++){const x=PILOT.glass.x0+.5+i;this.box(1,.12,1,x,this.ground(x,z)+.33,z,glass);}
 for(let i=0;i<=3;i++){const x=PILOT.glass.x0+i;this.box(.025,.1,4,x,this.ground(x,4)+.35,4,cyan);}for(const z of [2,6])this.box(3,.1,.04,-25.980762,this.ground(-25.980762,z)+.35,z,cyan);
 for(let x=-37;x<=-15;x+=4){this.box(.12,.12,5.7,x,-4.1,4,cyan);const light=new THREE.PointLight('#b7e7ed',11,9,2);light.position.set(x,-5,4);this.group.add(light);}
 this.box(3,.5,1.1,-34,-8.75,11,warm);this.box(2.4,.9,.1,-34,-7.7,11.5,cyan);for(const x of [-37,-31.8]){this.box(.8,.55,.8,x,-8.72,10,warm);this.world.catalogTree(this.group,x,-8.44,10,x===-37?1:2,'underground-room-'+x,1.1);}this.box(7,.2,5,-34.5,-4.9,9.5,base);const roomLight=new THREE.PointLight('#ffe3b4',18,10,2);roomLight.position.set(-34.5,-6,9.5);this.group.add(roomLight);
 for(const x of [-20,-18])this.box(.04,8,.04,x,-5,5,cyan);this.liftPlatform=this.box(2,.18,2,-19,-9.1,6,yellow);this.sign('ATELIER 01',-34.5,-5.6,7);this.sign('TRANSIT / ROAD RESERVE',-26,-5.3,1.04);this.sign('LIFT / ACCESS',-19,this.ground(-19,6)+1.4,6);
 const suit=this.mat('#e5bd80'),dark=this.mat('#20323c');const body=new THREE.Mesh(new THREE.CapsuleGeometry(.28,.65,5,10),suit);body.position.y=.95;this.avatar.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.3,14,10),suit);head.position.y=1.65;this.avatar.add(head);const visor=new THREE.Mesh(new THREE.BoxGeometry(.44,.18,.2),dark);visor.position.set(0,1.67,.23);this.avatar.add(visor);for(const x of [-.17,.17]){const foot=new THREE.Mesh(new THREE.BoxGeometry(.2,.45,.23),dark);foot.position.set(x,.3,0);this.avatar.add(foot);this.feet.push(foot);}this.avatar.scale.setScalar(.28);this.group.add(this.avatar);
 }
 private sign(_text:string,_x:number,_y:number,_z:number){/* Floating signs removed by owner request. */}
 setVisible(show:boolean){if(!show&&this.active)this.exit();this.group.visible=show;this.ui.hidden=!show;}
 enter(){if(this.active)return;if(this.world.mosaicChamber?.active)this.world.mosaicChamber.exit();this.active=true;this.oldPos.copy(this.world.camera.position);this.oldTarget.copy(this.world.controls.target);this.world.controls.enabled=false;this.avatar.visible=true;this.ui.querySelector<HTMLButtonElement>('.ug-start')!.hidden=true;this.world.renderer.domElement.parentElement!.classList.add('ug-active');this.ui.querySelector<HTMLDivElement>('.ug-panel')!.hidden=false;this.world.renderer.domElement.parentElement!.scrollIntoView({block:'start'});}
 exit(){this.active=false;this.world.renderer.domElement.parentElement!.classList.remove('ug-active');this.keys.clear();this.avatar.visible=false;this.world.controls.enabled=true;this.world.camera.position.copy(this.oldPos);this.world.controls.target.copy(this.oldTarget);this.ui.querySelector<HTMLButtonElement>('.ug-start')!.hidden=false;this.ui.querySelector<HTMLDivElement>('.ug-panel')!.hidden=true;}
 lift(){if(!this.active||this.movingLift)return;const atelier=this.level==='atelier'||Math.hypot(this.position.x+32,this.position.z-9.7)<1;if(atelier){this.liftKind='atelier';this.position.x=-32;this.position.z=9.7;this.liftGoal=this.level==='atelier'?PILOT.floor:-6.3;}else{if(this.level==='street'&&Math.hypot(this.position.x+19,this.position.z-6)>1.5)return;this.liftKind='surface';this.position.x=-19;this.position.z=6;this.liftGoal=this.level==='street'?this.ground(-19,6)+.48:PILOT.floor;}this.lookUp=false;this.movingLift=true;}

 update(dt:number){if(!this.active)return;dt=Math.min(dt,.1);if(this.movingLift){const delta=this.liftGoal-this.position.y;this.position.y+=Math.sign(delta)*Math.min(Math.abs(delta),dt*2.8);if(Math.abs(delta)<.02){this.position.y=this.liftGoal;this.level=this.liftGoal===PILOT.floor?'street':this.liftKind==='atelier'?'atelier':'surface';this.movingLift=false;}}else {this.yaw-=this.lookStick.x*dt*1.7;this.pitch=THREE.MathUtils.clamp(this.pitch-this.lookStick.y*dt*1.3,-1.1,1.1);const right=Number(this.keys.has('KeyD')||this.keys.has('ArrowRight'))-Number(this.keys.has('KeyA')||this.keys.has('ArrowLeft')),forward=Number(this.keys.has('KeyW')||this.keys.has('ArrowUp'))-Number(this.keys.has('KeyS')||this.keys.has('ArrowDown'));const movement=movementVector(this.yaw,right,forward),dx=movement.x,dz=movement.z;if(dx||dz){const n=Math.hypot(dx,dz),speed=1.9*dt;const x=this.position.x+dx/n*speed,z=this.position.z+dz/n*speed;if(this.level==='street'?walkable(x,this.position.z):this.level==='atelier'?inRect(x,this.position.z,{x0:-33.6,x1:-31.35,z0:8.5,z1:10.5},.12):inRect(x,this.position.z,{x0:-30,x1:-16,z0:2,z1:7},.25))this.position.x=x;if(this.level==='street'?walkable(this.position.x,z):this.level==='atelier'?inRect(this.position.x,z,{x0:-33.6,x1:-31.35,z0:8.5,z1:10.5},.12):inRect(this.position.x,z,{x0:-30,x1:-16,z0:2,z1:7},.25))this.position.z=z;this.avatar.rotation.y=Math.atan2(dx,dz);this.phase+=dt*8;this.feet.forEach((f,i)=>f.rotation.x=Math.sin(this.phase+i*Math.PI)*.4);}else this.feet.forEach(f=>f.rotation.x=0);if(this.level==='surface')this.position.y=this.ground(this.position.x,this.position.z)+.48;}
 this.atelierPlatform.position.y=this.liftKind==='atelier'&&this.movingLift?this.position.y-.08:this.level==='atelier'?-6.38:-9.08;this.liftPlatform.position.y=this.liftKind==='surface'&&this.movingLift?this.position.y-.1:this.level==='surface'?this.ground(-19,6)+.38:-9.1;this.avatar.visible=!this.eyeView;this.avatar.position.copy(this.position);this.ui.dataset.position=JSON.stringify({x:this.position.x,y:this.position.y,z:this.position.z,level:this.level,lift:this.movingLift});const room=this.position.z>7,near=Math.hypot(this.position.x+19,this.position.z-6)<1.5||Math.hypot(this.position.x+32,this.position.z-9.7)<1||this.level==='atelier';this.ui.querySelector('.ug-status')!.textContent=this.movingLift?'↕ מעבר במעלית':this.level==='atelier'?'אטלייה · מפלס פנימי 01':this.level==='surface'?'כיכר הכניסה · לכו מערבה אל הזכוכית':room?'אטלייה 01 · חדר ניסוי':'רחוב תת־קרקעי · מקום שמור לכביש';this.ui.querySelector<HTMLButtonElement>('[data-ug=lift]')!.disabled=!near||this.movingLift;
 const pos=this.position.clone().add(new THREE.Vector3(0,0,-4)),target=pos.clone().add(new THREE.Vector3(0,.45,0));const forward=new THREE.Vector3(-Math.sin(this.yaw)*Math.cos(this.pitch),Math.sin(this.pitch),-Math.cos(this.yaw)*Math.cos(this.pitch));
 let camera:THREE.Vector3,aim:THREE.Vector3;if(this.eyeView){camera=pos.clone().add(new THREE.Vector3(0,.5,0));aim=camera.clone().add(forward);}else if(this.lookUp&&this.level==='street'){camera=pos.clone().add(new THREE.Vector3(1,.5,1));aim=pos.clone().add(new THREE.Vector3(0,8,0));}else {camera=target.clone().add(new THREE.Vector3(Math.sin(this.yaw)*3.4,this.level==='surface'?5:1.5-this.pitch*1.5,Math.cos(this.yaw)*3.4));aim=target;if((this.level==='street'||this.level==='atelier')&&!this.movingLift){camera.x=THREE.MathUtils.clamp(camera.x,room?-37.7:-38.7,room?-31.3:-13.3);camera.z=THREE.MathUtils.clamp(camera.z,room?3.3:-2.7,room?7.7:2.7);camera.y=Math.min(camera.y,this.level==='atelier'?-5.15:-4.5);}}
 this.world.camera.position.copy(camera);this.world.camera.lookAt(aim);

 }
}
// Clip triangles at exact rectangular aperture edges, interpolating all vertex attributes.
export function cutApertures(g:THREE.BufferGeometry,cut:boolean,ox=0,oz=0){
 if(!g.userData.apertureOriginal){g.userData.apertureOriginal={index:Array.from(g.index!.array),attributes:Object.fromEntries(Object.entries(g.attributes).map(([k,a])=>[k,{size:a.itemSize,values:Array.from(a.array)}]))};}
 const original=g.userData.apertureOriginal as {index:number[];attributes:Record<string,{size:number;values:number[]}>};if(!cut){g.setIndex(original.index);for(const [k,a] of Object.entries(original.attributes))g.setAttribute(k,new THREE.Float32BufferAttribute(a.values,a.size));return;}
 const names=Object.keys(original.attributes),sizes=names.map(k=>original.attributes[k].size),offsets:number[]=[];let length=0;for(const n of sizes){offsets.push(length);length+=n;}const pOffset=offsets[names.indexOf('position')];const vertex=(id:number)=>names.flatMap(k=>{const a=original.attributes[k];return a.values.slice(id*a.size,(id+1)*a.size)});const values:Record<string,number[]>=Object.fromEntries(names.map(k=>[k,[]]));const indices:number[]=[];let count=0;
 const split=(poly:number[][],axis:number,bound:number)=>{const lo:number[][]=[],hi:number[][]=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],va=a[pOffset+axis],vb=b[pOffset+axis];(va<=bound?lo:hi).push(a);if((va<bound&&vb>bound)||(va>bound&&vb<bound)){const t=(bound-va)/(vb-va),v=a.map((n,k)=>n+(b[k]-n)*t);lo.push(v);hi.push(v);}}return [lo,hi];};
 const rects=[...[PILOT.glass,PILOT.shaft].map(r=>({...r,z0:r.z0-4,z1:r.z1-4})),...REVIEW_SHAFTS,...OCT10_SHAFTS,{x0:-15*Math.sqrt(3)-1.5,x1:-15*Math.sqrt(3)+1.5,z0:-2,z1:2}];for(let i=0;i<original.index.length;i+=3){let polys=[original.index.slice(i,i+3).map(vertex)];for(const r of rects){const out:number[][][]=[];for(const poly of polys){const xs=poly.map(v=>v[pOffset]+ox),zs=poly.map(v=>v[pOffset+2]+oz);if(Math.max(...xs)<=r.x0||Math.min(...xs)>=r.x1||Math.max(...zs)<=r.z0||Math.min(...zs)>=r.z1){out.push(poly);continue;}let candidates=[poly];for(const [axis,bound,keepLow] of [[0,r.x0-ox,true],[0,r.x1-ox,false],[2,r.z0-oz,true],[2,r.z1-oz,false]] as [number,number,boolean][]){const next:number[][][]=[];for(const p of candidates){const [lo,hi]=split(p,axis,bound),outside=keepLow?lo:hi,inside=keepLow?hi:lo;if(outside.length>=3)out.push(outside);if(inside.length>=3)next.push(inside);}candidates=next;}}polys=out;}for(const poly of polys){const start=count;for(const v of poly){names.forEach((k,j)=>values[k].push(...v.slice(offsets[j],offsets[j]+sizes[j])));count++;}for(let j=1;j<poly.length-1;j++)indices.push(start,start+j,start+j+1);}}
 for(const k of names)g.setAttribute(k,new THREE.Float32BufferAttribute(values[k],original.attributes[k].size));g.setIndex(indices);g.computeVertexNormals();
}


export type RoofWindow={x:number;z:number;radius:number;angle?:number};
// Subtract convex hex windows from surfaces while preserving interpolated vertex attributes.
export function cutRoofWindows(g:THREE.BufferGeometry,windows:RoofWindow[],ox=0,oz=0){
 const attrs=Object.entries(g.attributes),sizes=attrs.map(([,a])=>a.itemSize),offsets:number[]=[];let len=0;for(const n of sizes){offsets.push(len);len+=n;}const pi=offsets[attrs.findIndex(([k])=>k==='position')],values=attrs.map(()=>[] as number[]),indices:number[]=[];let count=0;const original=Array.from(g.index!.array);
 const vertex=(i:number)=>attrs.flatMap(([,a])=>Array.from({length:a.itemSize},(_,j)=>a.array[i*a.itemSize+j] as number));
 for(let i=0;i<original.length;i+=3){let polys=[original.slice(i,i+3).map(vertex)];for(const w of windows){const points=Array.from({length:6},(_,j)=>({x:w.x-ox+Math.cos(j*Math.PI/3+(w.angle??0))*w.radius,z:w.z-oz+Math.sin(j*Math.PI/3+(w.angle??0))*w.radius}));const out:number[][][]=[];for(const poly of polys){let inside=[poly];for(let j=0;j<6;j++){const a=points[j],b=points[(j+1)%6],cross=(v:number[])=> (b.x-a.x)*(v[pi+2]-a.z)-(b.z-a.z)*(v[pi]-a.x),next:number[][][]=[];for(const part of inside){const keep:number[][]=[],outside:number[][]=[];for(let k=0;k<part.length;k++){const u=part[k],v=part[(k+1)%part.length],cu=cross(u),cv=cross(v);(cu>=0?keep:outside).push(u);if(cu*cv<0){const t=cu/(cu-cv),p=u.map((n,k)=>n+(v[k]-n)*t);keep.push(p);outside.push(p);}}if(outside.length>=3)out.push(outside);if(keep.length>=3)next.push(keep);}inside=next;} }polys=out;}for(const poly of polys){const start=count;for(const v of poly){attrs.forEach((_,j)=>values[j].push(...v.slice(offsets[j],offsets[j]+sizes[j])));count++;}for(let j=1;j<poly.length-1;j++)indices.push(start,start+j,start+j+1);}}
 attrs.forEach(([k,a],j)=>g.setAttribute(k,new THREE.Float32BufferAttribute(values[j],a.itemSize)));g.setIndex(indices);g.computeVertexNormals();
}

export class MosaicChamber {
 active=false;group=new THREE.Group();private ui:HTMLDivElement;private center=new THREE.Vector3();private floor=0;private roof=0;private position=new THREE.Vector3();private oldPos=new THREE.Vector3();private oldTarget=new THREE.Vector3();private oldFov=48;private keys=new Set<string>();private look=true;private yaw=-Math.PI/4;private pitch=.15;private lookStick=new THREE.Vector2();
 constructor(private world:World){world.scene.add(this.group);this.group.name='mosaic-underground-chamber';this.ui=document.createElement('div');this.ui.className='mosaic-chamber-ui';this.ui.innerHTML='<button class="mc-enter">⌄ חלל הפסיפס</button><div class="mc-panel" hidden><strong>חלל הפסיפס · חיבור למעברים בעתיד</strong><div class="ug-switch"><button data-area="pilot" aria-pressed="false">מעברים</button><button data-area="mosaic" disabled aria-pressed="true">פסיפס</button></div><button class="mc-look">⇧ מבט אל החלונות</button><button class="mc-exit">מבט על ↗</button><small>WASD / חצים · Esc יציאה</small><div class="ug-pad"><button data-mc="north">▲</button><div><button data-mc="west">◀</button><button data-mc="south">▼</button><button data-mc="east">▶</button></div></div><div class="ug-look" aria-label="Look joystick"><span>מבט</span><i></i></div></div>';world.renderer.domElement.parentElement!.append(this.ui);this.ui.querySelector('[data-area=pilot]')!.addEventListener('click',()=>{this.exit();this.world.underground?.enter()});this.ui.querySelector('.mc-enter')!.addEventListener('click',()=>this.enter());this.ui.querySelector('.mc-exit')!.addEventListener('click',()=>this.exit());this.ui.querySelector('.mc-look')!.addEventListener('click',()=>this.look=!this.look);const stick=this.ui.querySelector<HTMLDivElement>('.ug-look')!;let lookId:number|undefined;const move=(e:PointerEvent)=>{if(e.pointerId!==lookId)return;const r=stick.getBoundingClientRect();this.lookStick.set(THREE.MathUtils.clamp((e.clientX-r.x-r.width/2)/(r.width/2),-1,1),THREE.MathUtils.clamp((e.clientY-r.y-r.height/2)/(r.height/2),-1,1));(stick.querySelector('i') as HTMLElement).style.transform=`translate(${this.lookStick.x*22}px,${this.lookStick.y*22}px)`;this.look=false;};stick.addEventListener('pointerdown',e=>{e.preventDefault();lookId=e.pointerId;stick.setPointerCapture(e.pointerId);move(e)});stick.addEventListener('pointermove',move);for(const ev of ['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(ev,()=>{lookId=undefined;this.lookStick.set(0,0);(stick.querySelector('i') as HTMLElement).style.transform='';});for(const b of Array.from(this.ui.querySelectorAll<HTMLButtonElement>('[data-mc]'))){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);this.keys.add(b.dataset.mc!)});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>this.keys.delete(b.dataset.mc!));}window.addEventListener('keydown',e=>{if(!this.active)return;if(e.code==='Escape')this.exit();if(['KeyW','KeyS','KeyA','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)){e.preventDefault();this.keys.add(e.code)}});window.addEventListener('keyup',e=>this.keys.delete(e.code));window.addEventListener('blur',()=>this.keys.clear());}
 configure(x:number,z:number,roof:number){if(this.active)this.exit();for(const o of [...this.group.children]){this.group.remove(o);o.traverse(o=>{if(o instanceof THREE.Mesh)o.geometry.dispose()});}this.center.set(x,0,z);this.roof=roof;this.floor=roof-5.5;const base=new THREE.MeshStandardMaterial({color:'#42555a',roughness:.72,side:THREE.DoubleSide}),wall=new THREE.MeshStandardMaterial({color:'#c1ae90',roughness:.8,side:THREE.DoubleSide}),glow=new THREE.MeshBasicMaterial({color:'#85d6e0'});const floor=new THREE.Mesh(new THREE.CylinderGeometry(9.85,9.85,.28,6),base);floor.position.set(x,this.floor-.14,z);this.group.add(floor);const shape=new THREE.Shape();for(let j=0;j<=6;j++){const a=j*Math.PI/3,px=Math.sin(a)*9.94,pz=Math.cos(a)*9.94;if(j===0)shape.moveTo(px,-pz);else shape.lineTo(px,-pz);}for(let t=0;t<7;t++){const a=((t-1)*Math.PI/3+Math.PI/6),rr=t===0?0:5.2,cx=Math.cos(a)*rr,cz=Math.sin(a)*rr,hole=new THREE.Path();for(let j=0;j<=6;j++){const a=j*Math.PI/3,px=cx+Math.cos(a)*2.95,pz=cz+Math.sin(a)*2.95;if(j===0)hole.moveTo(px,-pz);else hole.lineTo(px,-pz);}shape.holes.push(hole);}const roofGeo=new THREE.ShapeGeometry(shape);roofGeo.rotateX(-Math.PI/2);roofGeo.translate(x,roof-.015,z);const ceiling=new THREE.Mesh(roofGeo,base);this.group.add(ceiling);
 for(let j=0;j<6;j++){const a=j*Math.PI/3,b=(j+1)*Math.PI/3,ax=x+Math.sin(a)*9.85,az=z+Math.cos(a)*9.85,bx=x+Math.sin(b)*9.85,bz=z+Math.cos(b)*9.85,angle=Math.atan2(bz-az,bx-ax);const side=new THREE.Mesh(new THREE.BoxGeometry(9.85,5.5,.2),wall);side.position.set((ax+bx)/2,this.floor+2.75,(az+bz)/2);side.rotation.y=-angle;this.group.add(side);for(const y of [this.floor+.22,roof-.3]){const trim=new THREE.Mesh(new THREE.BoxGeometry(9.85,.06,.06),glow);trim.position.set((ax+bx)/2,y,(az+bz)/2);trim.rotation.y=-angle;this.group.add(trim);}}
 for(const dx of [-4,4])for(const dz of [-3,3]){const light=new THREE.PointLight('#c3e6ef',16,16,1.7);light.position.set(x+dx,this.floor+2.1,z+dz);this.group.add(light);}this.group.visible=true;this.ui.hidden=false;}
 setVisible(show:boolean){if(!show&&this.active)this.exit();this.group.visible=show;this.ui.hidden=!show;}
 enter(){if(this.active)return;if(this.world.underground?.active)this.world.underground.exit();this.active=true;this.oldFov=this.world.camera.fov;this.world.camera.fov=78;this.world.camera.updateProjectionMatrix();this.oldPos.copy(this.world.camera.position);this.oldTarget.copy(this.world.controls.target);this.world.controls.enabled=false;this.position.set(this.center.x-3,this.floor+1.6,this.center.z+3);this.look=true;this.yaw=-Math.PI/4;this.pitch=.15;this.lookStick.set(0,0);this.ui.querySelector<HTMLElement>('.mc-enter')!.hidden=true;this.ui.querySelector<HTMLElement>('.mc-panel')!.hidden=false;this.world.renderer.domElement.parentElement!.classList.add('ug-active');this.world.renderer.domElement.parentElement!.scrollIntoView({block:'start'});}
 exit(){if(!this.active)return;this.active=false;this.world.camera.fov=this.oldFov;this.world.camera.updateProjectionMatrix();this.keys.clear();this.lookStick.set(0,0);this.world.controls.enabled=true;this.world.camera.position.copy(this.oldPos);this.world.controls.target.copy(this.oldTarget);this.ui.querySelector<HTMLElement>('.mc-enter')!.hidden=false;this.ui.querySelector<HTMLElement>('.mc-panel')!.hidden=true;this.world.renderer.domElement.parentElement!.classList.remove('ug-active');}
 update(dt:number){if(!this.active)return;dt=Math.min(dt,.1);this.yaw-=this.lookStick.x*dt*1.7;this.pitch=THREE.MathUtils.clamp(this.pitch-this.lookStick.y*dt*1.3,-1.1,1.1);const right=Number(this.keys.has('east')||this.keys.has('KeyD')||this.keys.has('ArrowRight'))-Number(this.keys.has('west')||this.keys.has('KeyA')||this.keys.has('ArrowLeft')),forward=Number(this.keys.has('north')||this.keys.has('KeyW')||this.keys.has('ArrowUp'))-Number(this.keys.has('south')||this.keys.has('KeyS')||this.keys.has('ArrowDown')),v=movementVector(this.yaw,right,forward),n=Math.max(1,Math.hypot(v.x,v.z)),x=this.position.x+v.x/n*dt*2.5,z=this.position.z+v.z/n*dt*2.5;if(Math.hypot(x-this.center.x,z-this.center.z)<7.7){this.position.x=x;this.position.z=z;}this.world.camera.position.copy(this.position);const pitch=this.look?.95:this.pitch,aim=new THREE.Vector3(-Math.sin(this.yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(this.yaw)*Math.cos(pitch));this.world.camera.lookAt(this.position.clone().add(aim));this.ui.dataset.position=JSON.stringify({x:this.position.x,y:this.position.y,z:this.position.z,yaw:this.yaw,pitch:this.pitch});}
}
